### ISSUE TITLE
tests are getting loaded into application

### ISSUE THREAD

**Issue by skizzybiz** [bobes/sproutcore-coffeescript#1]
Nice gem, this is exactly what I was looking for. One small problem, though -- it loads all the scripts from my tests directory into the html, giving me test output instead of my application.

**Comment by bobes** [comment]
Thanks for the heads up, will have a look into it...

**Comment by skizzybiz** [comment]
Note, this is only happening in my TemplateView-based app. When I create a regular SproutCore app using the desktop framework, tests aren't a problem.
